baseURL = 'http://wilberhg.github.io/'
languageCode = 'pt-br'
title = '@wilberhg'
theme = "archie"
copyright = "© Wilberhg"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5

summaryLength = 20

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/wilber-h-godoy"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/wilhgodoy/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4